/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./../views/AboutView.vue')['default']
    AButton: typeof import('ant-design-vue/es')['Button']
    CarbonClose: typeof import('./../components/icon/CarbonClose.vue')['default']
    CarbonMoon: typeof import('./../components/icon/CarbonMoon.vue')['default']
    CarbonSettings: typeof import('./../components/icon/CarbonSettings.vue')['default']
    copy: typeof import('./../components/icons/IconTooling copy.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    HomeHead: typeof import('./../components/HomeHead.vue')['default']
    HomeView: typeof import('./../views/HomeView/index.vue')['default']
    IcBaselineWbSunny: typeof import('./../components/icon/IcBaselineWbSunny.vue')['default']
    IconCommunity: typeof import('./../components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../components/icons/IconEcosystem.vue')['default']
    IconFont: typeof import('./../components/icon/iconFont.vue')['default']
    IconMember: typeof import('./../components/icons/IconMember.vue')['default']
    IconSound: typeof import('./../components/icons/IconSound.vue')['default']
    IconSupport: typeof import('./../components/icons/IconSupport.vue')['default']
    'IconSupport copy': typeof import('./../components/icons/IconSupport copy.vue')['default']
    IconTooling: typeof import('./../components/icons/IconTooling.vue')['default']
    'IconTooling copy': typeof import('./../components/icons/IconTooling copy.vue')['default']
    LimboView: typeof import('./../views/LimboView/index.vue')['default']
    LogosBitriseIcon: typeof import('./../components/icon/LogosBitriseIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScratchView: typeof import('./../views/ScratchView/index.vue')['default']
    ScratchViewSingle: typeof import('./../views/ScratchViewSingle/index.vue')['default']
    SvgIcon: typeof import('./../components/icon/svgIcon.vue')['default']
    TheWelcome: typeof import('./../components/TheWelcome.vue')['default']
    Welcome: typeof import('./../components/Welcome.vue')['default']
    WelcomeItem: typeof import('./../components/WelcomeItem.vue')['default']
  }
}
